apiVersion: v1
kind: Namespace
metadata:
  name: prd
---
apiVersion: v1
kind: Service
metadata:
  name: reca1team-web-server
  namespace: prd 
  labels:
    app: web-server
spec:
  type: NodePort
  selector:
    app: web-server
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: prd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: reca1team-web-server
          image: 891377163278.dkr.ecr.ap-northeast-2.amazonaws.com/jenkins:frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: reca1team-web-server-hpa
  namespace: prd
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-server
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 40

---
apiVersion: v1
kind: Service
metadata:
  name: reca1team-was-server
  namespace: prd
  labels:
    app: was-server
spec:
  type: ClusterIP
  selector:
    app: was-server
  ports:
  - port: 8888
    targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: was-server
  namespace: prd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: was-server
  template:
    metadata:
      labels:
        app: was-server
    spec:
      containers:
      - name: reca1team-was-server
        image: 891377163278.dkr.ecr.ap-northeast-2.amazonaws.com/jenkins:backend-v2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: reca1team-was-server-hpa
  namespace: prd
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: was-server
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 40
